FROM golang:1.23-alpine AS build
WORKDIR /src
RUN apk add --no-cache ca-certificates git
ENV GOPROXY=https://goproxy.io,direct
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o /server ./cmd/server

FROM alpine:latest
RUN apk add --no-cache ca-certificates tzdata wget
ENV TZ=Asia/Tehran
COPY --from=build /server /server
EXPOSE 8080
USER nobody
CMD ["/server"]
