package notify

var dict = map[string]map[string]string{
	"fa": {
		"kb.overview": "📊 خلاصه",
		"kb.accounts": "💳 حساب‌ها",
		"kb.assets":   "💎 دارایی‌ها",
		"kb.debts":    "📉 بدهی‌ها",
		"kb.projects": "📁 پروژه‌ها",
		"kb.expense":  "➖ هزینه",
		"kb.income":   "➕ درآمد",
		"kb.transfer": "↔️ انتقال",
		"kb.menu":     "🏠 منو",
		"home.title":  "PVMoney — خزانه‌دار تلگرامی تو",
		"home.body":   "از دکمه‌های پایین برای دیدن مانده‌ها و ثبت تراکنش استفاده کن.\nهر تغییری در سایت هم همین‌جا پیام می‌آید.",
		"btn.overview": "📊 خلاصه",
		"btn.accounts": "💳 حساب‌ها",
		"btn.assets":   "💎 دارایی‌ها",
		"btn.debts":    "📉 بدهی‌ها",
		"btn.projects": "📁 پروژه‌ها",
		"btn.recent":   "📜 آخرین تراکنش‌ها",
		"btn.expense":  "➖ هزینه جدید",
		"btn.income":   "➕ درآمد جدید",
		"btn.transfer": "↔️ انتقال",
		"btn.lang":     "🌐 زبان ربات",
		"btn.back":     "⬅️ بازگشت",
		"btn.cancel":   "انصراف",
		"btn.skip":     "رد کردن",
		"btn.ok":       "✅ تایید",
		"btn.pay":      "پرداخت قسط",
		"lang.title":   "زبان منوی ربات را انتخاب کن.\nاعلان‌های سایت همیشه انگلیسی + آلمانی هستند.",
		"empty.acc":    "حسابی ثبت نشده. اول از سایت یک حساب بساز.",
		"empty.asset":  "دارایی ثبت نشده.",
		"empty.debt":   "بدهی‌ای باقی نمانده.",
		"empty.proj":   "پروژه‌ای نیست.",
		"empty.tx":     "تراکنشی نیست.",
		"overview":     "نگاه کلی",
		"net":          "ارزش خالص",
		"liquid":       "نقد و حساب‌ها",
		"assets":       "دارایی‌ها",
		"debts":        "بدهی باقی‌مانده",
		"monthIn":      "درآمد این ماه",
		"monthOut":     "هزینه این ماه",
		"nextDue":      "قسط بعدی",
		"accounts":     "حساب‌ها",
		"assetsT":      "دارایی‌ها",
		"debtsT":       "بدهی‌ها",
		"projects":     "پروژه‌ها",
		"recent":       "آخرین تراکنش‌ها",
		"paid":         "تسویه",
		"active":       "فعال",
		"spent":        "خرج",
		"tx.pickType":  "چه تراکنشی ثبت شود؟",
		"tx.pickAcc":   "از کدام حساب؟",
		"tx.pickTo":    "به کدام حساب؟",
		"tx.pickCat":   "دسته‌بندی را انتخاب کن:",
		"tx.amount":    "مبلغ را بفرست.\nمثال: 2500000 یا 2.5m یا ۲٫۵ میلیون",
		"tx.note":      "توضیح؟ می‌توانی بنویسی یا رد کنی.",
		"tx.confirm":   "تایید می‌کنی؟",
		"tx.saved":     "ثبت شد.",
		"tx.needTwo":   "برای انتقال حداقل دو حساب لازم است.",
		"tx.badAmt":    "مبلغ را نفهمیدم. مثلاً 3m یا 3000000 بفرست.",
		"tx.cancelled": "لغو شد.",
		"pay.none":     "قسط بازی برای پرداخت نیست.",
		"pay.pickAcc":  "پرداخت از کدام حساب؟",
		"pay.confirm":  "پرداخت قسط تایید شود؟",
		"pay.ok":       "قسط پرداخت شد.",
		"type.expense": "هزینه",
		"type.income":  "درآمد",
		"type.transfer": "انتقال",
		"help.unknown": "از دکمه‌های پایین استفاده کن یا /menu را بزن.",
	},
	"en": {
		"kb.overview": "📊 Overview",
		"kb.accounts": "💳 Accounts",
		"kb.assets":   "💎 Assets",
		"kb.debts":    "📉 Debts",
		"kb.projects": "📁 Projects",
		"kb.expense":  "➖ Expense",
		"kb.income":   "➕ Income",
		"kb.transfer": "↔️ Transfer",
		"kb.menu":     "🏠 Menu",
		"home.title":  "PVMoney — your Telegram treasurer",
		"home.body":   "Use the buttons below to check balances and add transactions.\nEvery change in the app is also pushed here.",
		"btn.overview": "📊 Overview",
		"btn.accounts": "💳 Accounts",
		"btn.assets":   "💎 Assets",
		"btn.debts":    "📉 Debts",
		"btn.projects": "📁 Projects",
		"btn.recent":   "📜 Recent",
		"btn.expense":  "➖ New expense",
		"btn.income":   "➕ New income",
		"btn.transfer": "↔️ Transfer",
		"btn.lang":     "🌐 Bot language",
		"btn.back":     "⬅️ Back",
		"btn.cancel":   "Cancel",
		"btn.skip":     "Skip",
		"btn.ok":       "✅ Confirm",
		"btn.pay":      "Pay installment",
		"lang.title":   "Choose the bot menu language.\nApp notifications stay English + German.",
		"empty.acc":    "No accounts yet. Add one in the app first.",
		"empty.asset":  "No assets yet.",
		"empty.debt":   "No remaining debts.",
		"empty.proj":   "No projects.",
		"empty.tx":     "No transactions.",
		"overview":     "Overview",
		"net":          "Net worth",
		"liquid":       "Cash & accounts",
		"assets":       "Assets",
		"debts":        "Remaining debts",
		"monthIn":      "Income this month",
		"monthOut":     "Expenses this month",
		"nextDue":      "Next due",
		"accounts":     "Accounts",
		"assetsT":      "Assets",
		"debtsT":       "Debts",
		"projects":     "Projects",
		"recent":       "Recent transactions",
		"paid":         "Paid",
		"active":       "Active",
		"spent":        "spent",
		"tx.pickType":  "What do you want to add?",
		"tx.pickAcc":   "Which account?",
		"tx.pickTo":    "To which account?",
		"tx.pickCat":   "Pick a category:",
		"tx.amount":    "Send the amount.\nExamples: 2500000 or 2.5m",
		"tx.note":      "A note? Type one or skip.",
		"tx.confirm":   "Confirm this?",
		"tx.saved":     "Saved.",
		"tx.needTwo":   "You need at least two accounts to transfer.",
		"tx.badAmt":    "I couldn’t read that amount. Try 3m or 3000000.",
		"tx.cancelled": "Cancelled.",
		"pay.none":     "No open installment to pay.",
		"pay.pickAcc":  "Pay from which account?",
		"pay.confirm":  "Confirm installment payment?",
		"pay.ok":       "Installment paid.",
		"type.expense": "Expense",
		"type.income":  "Income",
		"type.transfer": "Transfer",
		"help.unknown": "Use the buttons below, or send /menu.",
	},
	"de": {
		"kb.overview": "📊 Übersicht",
		"kb.accounts": "💳 Konten",
		"kb.assets":   "💎 Vermögen",
		"kb.debts":    "📉 Schulden",
		"kb.projects": "📁 Projekte",
		"kb.expense":  "➖ Ausgabe",
		"kb.income":   "➕ Einnahme",
		"kb.transfer": "↔️ Überweisung",
		"kb.menu":     "🏠 Menü",
		"home.title":  "PVMoney — dein Telegram-Schatzmeister",
		"home.body":   "Mit den Buttons unten siehst du Salden und buchst Zahlungen.\nJede Änderung in der App kommt auch hier an.",
		"btn.overview": "📊 Übersicht",
		"btn.accounts": "💳 Konten",
		"btn.assets":   "💎 Vermögen",
		"btn.debts":    "📉 Schulden",
		"btn.projects": "📁 Projekte",
		"btn.recent":   "📜 Letzte",
		"btn.expense":  "➖ Neue Ausgabe",
		"btn.income":   "➕ Neue Einnahme",
		"btn.transfer": "↔️ Überweisung",
		"btn.lang":     "🌐 Bot-Sprache",
		"btn.back":     "⬅️ Zurück",
		"btn.cancel":   "Abbrechen",
		"btn.skip":     "Überspringen",
		"btn.ok":       "✅ Bestätigen",
		"btn.pay":      "Rate zahlen",
		"lang.title":   "Sprache des Bot-Menüs wählen.\nApp-Benachrichtigungen bleiben Englisch + Deutsch.",
		"empty.acc":    "Noch keine Konten. Lege zuerst eins in der App an.",
		"empty.asset":  "Kein Vermögen erfasst.",
		"empty.debt":   "Keine offenen Schulden.",
		"empty.proj":   "Keine Projekte.",
		"empty.tx":     "Keine Buchungen.",
		"overview":     "Übersicht",
		"net":          "Nettovermögen",
		"liquid":       "Bargeld & Konten",
		"assets":       "Vermögen",
		"debts":        "Offene Schulden",
		"monthIn":      "Einnahmen diesen Monat",
		"monthOut":     "Ausgaben diesen Monat",
		"nextDue":      "Nächste Fälligkeit",
		"accounts":     "Konten",
		"assetsT":      "Vermögen",
		"debtsT":       "Schulden",
		"projects":     "Projekte",
		"recent":       "Letzte Buchungen",
		"paid":         "Getilgt",
		"active":       "Aktiv",
		"spent":        "ausgegeben",
		"tx.pickType":  "Was möchtest du buchen?",
		"tx.pickAcc":   "Welches Konto?",
		"tx.pickTo":    "Auf welches Konto?",
		"tx.pickCat":   "Kategorie wählen:",
		"tx.amount":    "Betrag senden.\nBeispiele: 2500000 oder 2.5m",
		"tx.note":      "Notiz? Tippen oder überspringen.",
		"tx.confirm":   "Bestätigen?",
		"tx.saved":     "Gespeichert.",
		"tx.needTwo":   "Für eine Überweisung brauchst du mindestens zwei Konten.",
		"tx.badAmt":    "Betrag nicht erkannt. Versuche 3m oder 3000000.",
		"tx.cancelled": "Abgebrochen.",
		"pay.none":     "Keine offene Rate.",
		"pay.pickAcc":  "Von welchem Konto zahlen?",
		"pay.confirm":  "Ratenzahlung bestätigen?",
		"pay.ok":       "Rate bezahlt.",
		"type.expense": "Ausgabe",
		"type.income":  "Einnahme",
		"type.transfer": "Überweisung",
		"help.unknown": "Nutze die Buttons unten oder sende /menu.",
	},
}

func tr(lang, key string) string {
	if m, ok := dict[lang]; ok {
		if v, ok := m[key]; ok {
			return v
		}
	}
	if v, ok := dict["en"][key]; ok {
		return v
	}
	return key
}

func (b *Bot) isBtn(text, key string) bool {
	for _, loc := range []string{"fa", "en", "de"} {
		if text == tr(loc, key) {
			return true
		}
	}
	return false
}

type cat struct {
	ID string
	FA string
	EN string
	DE string
}

var expenseCats = []cat{
	{"food", "خوراک", "Food", "Essen"},
	{"transport", "حمل‌ونقل", "Transport", "Transport"},
	{"housing", "مسکن", "Housing", "Wohnen"},
	{"bills", "قبوض", "Bills", "Rechnungen"},
	{"shopping", "خرید", "Shopping", "Einkauf"},
	{"health", "درمان", "Health", "Gesundheit"},
	{"fun", "سرگرمی", "Fun", "Freizeit"},
	{"education", "آموزش", "Education", "Bildung"},
	{"other_expense", "سایر", "Other", "Sonstiges"},
}

var incomeCats = []cat{
	{"salary", "حقوق", "Salary", "Gehalt"},
	{"freelance", "فریلنس", "Freelance", "Freelance"},
	{"investment", "سود سرمایه", "Investment", "Anlage"},
	{"gift", "هدیه", "Gift", "Geschenk"},
	{"sale", "فروش", "Sale", "Verkauf"},
	{"other_income", "سایر", "Other", "Sonstiges"},
}

func (c cat) label(lang string) string {
	switch lang {
	case "fa":
		return c.FA
	case "de":
		return c.DE
	default:
		return c.EN
	}
}
